bind=SUPER,p,toggle_named_scratchpad,py-calculator,none,nix-shell ~/.config/mango/src/scratchpads/py-calculator.nix
windowrule=isnamedscratchpad:1,width:1380,height:820,appid:calculator

bind=SUPER,n,toggle_named_scratchpad,notes,none,zennotes-desktop
windowrule=isnamedscratchpad:1,width:1380,height:820,appid:notes
