source=./src/bind.conf
source=./src/decorations.conf
source=./src/devices.conf
source=./src/layout.conf
source=./src/misc.conf
source=./src/rules.conf
source=./src/tag.conf
source=./src/scratchpads/scratchpads.conf

exec-once=systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=systemctl --user start wallpaper.service
exec-once=vibepanel -c /etc/xdg/vibepanel/primary/config.toml
exec-once=vibepanel -c /etc/xdg/vibepanel/secondary/config.toml
#exec-once=quickshell -p "/etc/xdg/bar/shell.qml"
exec-once=bash ~/.config/home-manager/apps/mango/src/src/auto_start.sh
exec-once=elephant &
exec-once=walker -gapplication-service
