bind_to_address "/run/user/1000/mpd/socket"
music_directory "~/music"

playlist_directory      "~/Media/mpd/playlists"
auto_update "yes"

audio_output {
    type "alsa"
    name "Topping E30 II"
    device "hw:CARD=II,DEV=0"
    auto_resample   "no"
    auto_format     "no"
    auto_channels   "no"
    mixer_type      "none"
}

